name: graphml
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - networkx
  - python-igraph>=0.7.1
  - matplotlib
  - seaborn
  - scipy
  - numpy
  - biopython
  - pytorch
  - pytorch_scatter
  - pytorch_sparse
  - pytorch_geometric
  - jupyterlab
